### ISSUE TITLE
Not able to run locally

### ISSUE THREAD

**Issue by vigneshs-dev** [KorryKatti/Mirage#10]
I tried to run your project by forking the repository and following the given steps. But I got the 404 - Not found error. I used to install requirements.txt file on normal and .venv modes. On both the times, I am not able to get the output. Can you please solve this problem?

And after solving this issue, I like to contribute by updating the README.md file for running this project locally.

**Comment by KorryKatti** [comment]
its the server url , its not meant to be run anyways so it will display 404.

**Comment by vigneshs-dev** [comment]
> its the server url , its not meant to be run anyways so it will display 404.

Then how can I run this chat app locally to get an idea. Can you give me the steps to do that?

**Comment by KorryKatti** [comment]
run server file then run client file

**Comment by vigneshs-dev** [comment]
> run server file then run client file

Thankyou. It's working fine now.
