### ISSUE TITLE
Integrated api docs and Api Testing environment Setup by swagger Ui

### ISSUE THREAD

**Issue by Adeesh-bode** [KorryKatti/Mirage#15]

**Comment by KorryKatti** [comment]
provide more context

**Comment by Adeesh-bode** [comment]
Integrated API Docs and API Testing Environment Setup with Swagger UI

Swagger UI is a tool that allows developers to visualize and interact with APIs through a web interface. It automatically generates interactive documentation based on API specifications written in OpenAPI format. Here’s a brief overview of its setup and features:

API Documentation:

Swagger UI generates user-friendly documentation directly from the OpenAPI specification (usually in JSON or YAML format).
Users can explore API endpoints, required parameters, and response formats.
Interactive Testing:

Users can execute API calls directly from the documentation interface.
This feature helps developers test endpoints in real-time, making it easier to debug and verify API functionality.
Setup Process:

Install Swagger UI: It can be integrated into your project via npm, Docker, or by downloading the static files.
Create OpenAPI Specification: Define your API endpoints, parameters, and responses in an OpenAPI document.
Configure Swagger UI: Point Swagger UI to your OpenAPI spec file, allowing it to render the documentation.
Benefits:

Simplifies API understanding for both developers and non-technical stakeholders.
Streamlines the development process with immediate feedback during testing.
In essence, Swagger UI combines comprehensive documentation with an interactive testing environment, enhancing the API development and consumption experience.

**Comment by KorryKatti** [comment]
so you are making documentation ?

**Comment by Adeesh-bode** [comment]
Api documentation are different , they also solve the purpose of api testing

**Comment by Adeesh-bode** [comment]
Explore Swagger Ui , you will understand

**Comment by KorryKatti** [comment]
> Explore Swagger Ui , you will understand

i will , and when need arises i will reopen this issue , thank you for the information
