### ISSUE TITLE
2nd ISSUE

### ISSUE THREAD

**Issue by KorryKatti** [KorryKatti/Mirage#16]
🎉 **The Most Awaited Second Issue is Here!** 🎉

🔥 Introducing the **`server.py` Update Challenge** for our chat app, Mirage! We're looking for contributors to help evolve the server. Please keep these points in mind before diving in:

### 🚀 **What We're Looking For:**
1. **Flask Framework:** The current `server.py` uses Flask. If you decide to proceed with Flask, there’s no need to modify `client.py`.
2. **SocketIO Transition:** Many contributors have shown interest in switching to SocketIO. If you choose this path, we'd appreciate it if you also update `client.py` accordingly to maintain compatibility.

### 💡 **Key Features to Retain:**
These are the core aspects that make Mirage unique. You're free to **improvise** and make things better—just keep the essence intact!
1. Messages are **temporarily stored** on the server until all clients receive them, and then they're **deleted**.
2. All data (like rooms and user counts) is stored in a **JSON file**—no databases, keeping it simple and lightweight.
3. No **authentication** is involved now, nor is it planned for the future.
4. **No chat logs**—privacy is a core feature.

Feel free to enhance anything else while maintaining the current functionality!

---

**🔍 PLEASE CHECK YOUR CODE BEFORE SUBMITTING A PR**

Thank you so much for your contributions. Enjoy Hacktoberfest! 🌿✨

> 🚨 Note: The **client UI modification** issue is still open. If a server PR is accepted, the UI issue will be closed for now and reopened later.

🔒 **Security features integration** will be the next exciting challenge once the server updates are complete, so stay tuned!

🌟 **Don't forget to star the repo!** 🌟

**Comment by eleensmathew** [comment]
Can I work on this? Also can you provide more details about the issue?

**Comment by KorryKatti** [comment]
> Can I work on this? Also can you provide more details about the issue?

you can work on it , what details would you like to know exactly ?

**Comment by eleensmathew** [comment]
What exact feature do i need to implement? which file do i need to change? Do i need to write tests?

**Comment by KorryKatti** [comment]
> What exact feature do i need to implement? which file do i need to change? Do i need to write tests?

the server.py needs to be modified for better performance , you may use socketio but that will then need client modifications , so i suggest sticking to flask. No need to write tests , just clone the repo , make your changes , test the app and if it works go for a PR , i will check if its working under the required guidelines and then check if their has been any performance improvement or any more good improvements. If yes i will be approving it.

**Comment by eleensmathew** [comment]
I see that you are storing the messages on a dict called messages. If this website is hosted on a central server, all these messages can be accessed by the website admin as these messages aren't encrypted.

**Comment by KorryKatti** [comment]
> I see that you are storing the messages on a dict called messages. If this website is hosted on a central server, all these messages can be accessed by the website admin as these messages aren't encrypted.

yes , i would like the dict to be autocleared after a certain time period , also encryption is in my mind but i think i will make a separate issue for that under security fixes but i wouldn't mind if the encryption issue is fixed right now too

**Comment by eleensmathew** [comment]
Shall i add a timestamp to these messages and clear messages older than 1 hour?
I'll try adding encryption as well.

**Comment by eleensmathew** [comment]
Also I have noticed that when I change to a new user, I am still able to see the chats and rooms of the previous user. Shall i change this?

**Comment by KorryKatti** [comment]
> Shall i add a timestamp to these messages and clear messages older than 1 hour? I'll try adding encryption as well.

that would be awesome , also be sure to checkout the client code to see if your methods are in proper sync

**Comment by ayushmankoley** [comment]
Hello I would like to work on this issue please assign it

**Comment by eleensmathew** [comment]
Hi @ayushmankoley i am working on this issue currently

**Comment by ayushmankoley** [comment]
@eleensmathew both of us can solve this issue and send a pr, host can choose the best one which will be merged

**Comment by eleensmathew** [comment]
Hi @ayushmankoley in the best interest of hacktoberfest, there is no need for a race to finish resolving the issue. There are multiple performance improvements that can be made in this repository. You can make an issue and start contributing

**Comment by KorryKatti** [comment]
> Hi @ayushmankoley in the best interest of hacktoberfest, there is no need for a race to finish resolving the issue. There are multiple performance improvements that can be made in this repository. You can make an issue and start contributing

I agree with you , first pr first accepted doesn't mean your pr will be instantly accepted. The one which fixes the most will be accepted first , i usually wait 24 hours before merging/closing a pr if there are more than 1 people working on it so good luck

**Comment by ayushmankoley** [comment]
@KorryKatti thanks for the clarification, I will start working on this

**Comment by ayushmankoley** [comment]
Hey @KorryKatti, please unassign me from this issue as I see the issue I was going to work on has been solved already, I will choose some other issue to work on

**Comment by KorryKatti** [comment]
> Hey @KorryKatti, please unassign me from this issue as I see the issue I was going to work on has been solved already, I will choose some other issue to work on

sure
