### ISSUE TITLE
1st ISSUE 

### ISSUE THREAD

**Issue by KorryKatti** [KorryKatti/Mirage#2]
# Issue: Improve the UI of Mirage

**Description:**

The current UI of Mirage could use some enhancements to make it more user-friendly and visually appealing. The UI code is located in the `client.py` file. Your task is to improve the UI design while keeping the core functionality unchanged.

**Requirements:**

- The updated UI should **not change the core functionality** of the chat application.
- You are **only allowed** to use the following for making improvements to the UI:
  1. **Tkinter**
  2. **CustomTkinter**
  3. **Flask backend with HTML frontend**
  4. **TTKBootstrap**

Feel free to be creative and make the UI more modern and visually engaging, but make sure that no core features or functionality of the app are removed or altered.

**Guidelines:**

1. Fork the repository.
2. Create a new branch to work on the issue.
3. Make your changes and commit them.
4. Submit a pull request (PR) referencing this issue.

**First-Come, First-Served:** The pull request that improves the UI while fulfilling all requirements and is submitted first will be accepted.

**Good luck, and happy coding!** 🎨✨

[ PR acceptance may take time since i am very busy right now ]

**Comment by KorryKatti** [comment]
If you need any help you can find me [here](https://discord.gg/xgGDNEw3FY) or directly dm me on discord

**Comment by Zingzy** [comment]
Hello, I can help, I will use customTkinter to update the GUI. I have good experience in creating modern GUI's with customTkinter. Please assign me this issue.

**Comment by shubhagarwal1** [comment]
i can collab with @Zingzy and start working on ui enhacements @KorryKatti

**Comment by KorryKatti** [comment]
alright assigning to you both

**Comment by KorryKatti** [comment]
done

**Comment by KorryKatti** [comment]
Please remember its first done first approved

**Comment by shubhagarwal1** [comment]
> Hello, I can help, I will use customTkinter to update the GUI. I have good experience in creating modern GUI's with customTkinter. Please assign me this issue.

hey @Zingzy how can we connect

**Comment by Zingzy** [comment]
> > Hello, I can help, I will use customTkinter to update the GUI. I have good experience in creating modern GUI's with customTkinter. Please assign me this issue.
> 
> hey @Zingzy how can we connect 

Hello @shubhagarwal1 unfortunately this is not how hacktoberfest works, only 1 person can one issue :/

**Comment by shubhagarwal1** [comment]
> > > Hello, I can help, I will use customTkinter to update the GUI. I have good experience in creating modern GUI's with customTkinter. Please assign me this issue.
> > 
> > 
> > hey @Zingzy how can we connect
> 
> Hello @shubhagarwal1 unfortunately this is not how hacktoberfest works, only 1 person can work on one issue :/

okay then i will work on improving specific part of the ui then you can work likewise.

**Comment by Zingzy** [comment]
> > > > Hello, I can help, I will use customTkinter to update the GUI. I have good experience in creating modern GUI's with customTkinter. Please assign me this issue.
> > > 
> > > 
> > > hey @Zingzy how can we connect
> > 
> > Hello @shubhagarwal1 unfortunately this is not how hacktoberfest works, only 1 person can work on one issue :/
> 
> okay then i will work on improving specific part of the ui then you can work likewise.

No worries you can work on this issue alone @shubhagarwal1 , @KorryKatti please unassign me

**Comment by KorryKatti** [comment]
looks like you did it yourself. have fun

**Comment by KorryKatti** [comment]
> Hello please assign me this issue.

this is not the web ui , its the python ui , you sure you want it ?

**Comment by Garrett04** [comment]
Yep python UI.. I know it's first come first come first served. But I'm willing to learn some python UI either way. 😄

**Comment by KorryKatti** [comment]
> Oh sorry, I would've still taken this up... But am busy with other things at the moment.

no problem
