### ISSUE TITLE
For newcomers |  Implement a Statistics Feature

### ISSUE THREAD

**Issue by KorryKatti** [KorryKatti/Mirage#20]
### Overview
I would like to implement a **statistics feature** that tracks pings to the server. This feature will provide simple metrics about client interactions. Here's how it will work:

### Steps to Implement

1. **JSON File Creation**: 
   - The server will create an empty JSON file with two keys: `total` and `today`.
  
2. **Client Ping**:
   - The client will ping the server's **metrics endpoint**.

3. **Record Metrics**:
   - Upon receiving a ping, the server will:
     - Record the timestamp of the ping.
     - Increment `total` by +1.
     - Increment `today` by +1.

4. **Daily Reset**:
   - The `today` entry will reset every 24 hours. For example:
     - If you ping the server at 8 AM and your friend pings at 9 AM, your ping will be deleted the next day at 8:30 AM, while your friend's will remain.

5. **Single Ping Check**:
   - The client should ensure that only **one ping** is sent every 24 hours.

### Additional Notes
- You will need to create the metrics endpoint in `server.py`, and the server should ensure the necessary JSON file is created if it doesn’t already exist.
- If you wish to expand upon this feature (e.g., adding more metrics), please leave a comment, and I will review it!

**Comment by KorryKatti** [comment]
> Would like to work on that ;)

good , i will assign it to you , looking for to the PR

**Comment by mironbarykin** [comment]
back here again, please provide me with some detailed information about the idea of "pinging", because it is not clear for me why the statistics of "pings" is supposed to be recorded on endpoint calls and why is it supposed to be blocked (if last ping was not earlier than 24 hours from now) on the client side when it seems rational to do that on the server side instead.

However the PR I sent is assumed to implement basic abilities of saving, recording and updaing the statistics on our need.

**Comment by KorryKatti** [comment]
1. i want to make a kind of total users and daily visitors stats on the website of it
2.  Because we have no way to validate user at the server we will ask the client to block it if it is under 24 hours 


I am not sure i understood your question fully tho so please correct me or ask me more

**Comment by mironbarykin** [comment]
Alright, then I will make some changes to the code.

**Comment by KorryKatti** [comment]
> Alright, then I will make some changes to the code.

glad i could explain it , happy coding

**Comment by KorryKatti** [comment]
Done now , stay tuned for new issues
