### ISSUE TITLE
Improving the server | open to all 

### ISSUE THREAD

**Issue by KorryKatti** [KorryKatti/Mirage#23]
🎉 **The Most Awaited Second Issue is Here!** 🎉

🔥 Introducing the **`server.py` Update Challenge** for our chat app, Mirage! We're looking for contributors to help evolve the server. Please keep these points in mind before diving in:

### 🚀 **What We're Looking For:**
1. **Flask Framework:** The current `server.py` uses Flask. If you decide to proceed with Flask, there’s no need to modify `client.py`.
2. **SocketIO Transition:** Many contributors have shown interest in switching to SocketIO. If you choose this path, we'd appreciate it if you also update `client.py` accordingly to maintain compatibility.

### 💡 **Key Features to Retain:**
These are the core aspects that make Mirage unique. You're free to **improvise** and make things better—just keep the essence intact!
1. Messages are **temporarily stored** on the server until all clients receive them, and then they're **deleted**.
2. All data (like rooms and user counts) is stored in a **JSON file**—no databases, keeping it simple and lightweight.
3. No **authentication** is involved now, nor is it planned for the future.
4. **No chat logs**—privacy is a core feature.

Feel free to enhance anything else while maintaining the current functionality!

---

**🔍 PLEASE CHECK YOUR CODE BEFORE SUBMITTING A PR**

Thank you so much for your contributions. Enjoy Hacktoberfest! 🌿✨

> 🚨 Note: The **client UI modification** issue is still open. If a server PR is accepted, the UI issue will be closed for now and reopened later.

🔒 **Security features integration** will be the next exciting challenge once the server updates are complete, so stay tuned!

🌟 **Don't forget to star the repo!** 🌟

**Comment by Manbendra2014** [comment]
Hey ! I'd be happy to help you with converting your code to use Socket Programming.

**Comment by KorryKatti** [comment]
> Hey ! I'd be happy to help you with converting your code to use Socket Programming.

noted

**Comment by KorryKatti** [comment]
Server has been switched to socketio , closing this issue now
