### ISSUE TITLE
Security enhancements

### ISSUE THREAD

**Issue by anadevti** [KorryKatti/Mirage#24]
*Adding encryption to messages to ensure the privacy of user data during message exchanges.*
#
I will use the PyCryptodome library

**Comment by KorryKatti** [comment]
> _Adding encryption to messages to ensure the privacy of user data during message exchanges._
> 
> I will use the PyCryptodome library

i was about to open this issue after the server issue ends so could you wait 2 more days ? I will notify you of it when it starts.

**Comment by anadevti** [comment]
> > _Adding encryption to messages to ensure the privacy of user data during message exchanges._
> > I will use the PyCryptodome library
> 
> i was about to open this issue after the server issue ends so could you wait 2 more days ? I will notify you of it when it starts.

Yes, I can wait, no problem! 😊
