### ISSUE TITLE
Question for the saving message and the main idea of this application

### ISSUE THREAD

**Issue by kwunhang** [KorryKatti/Mirage#25]
For #18 
If when the server restart, I think the message should assume disappear. Since in the readme, you mentioned that "storing messages on the server" and "Messages are never stored on the server permanently , ensuring that your conversations remain private." It is quite weird to store the message in server and against to the purpose of privacy.
@KorryKatti

**Comment by KorryKatti** [comment]
> For #18 If when the server restart, I think the message should assume disappear. Since in the readme, you mentioned that "storing messages on the server" and "Messages are never stored on the server permanently , ensuring that your conversations remain private." It is quite weird to store the message in server and against to the purpose of privacy. @KorryKatti

the client saves the messages it received on the client side in a folder named messages , messages aren't stored on the server, when the server restarts the client software should read the message from the files present at client side.

i hope it makes sense but i will be glad to elaborate if you have any more doubts
