### ISSUE TITLE
web ui

### ISSUE THREAD

**Issue by KorryKatti** [KorryKatti/Mirage#29]
# 🚨 Web UI Development Update 🚨

I am excited to announce that the **Web UI for Mirage will be developed in a separate repository**! 🎉

If you're interested in contributing to this part of the project, please feel free to visit the dedicated repo:

👉 [Mirage Web UI Repository](https://github.com/KorryKatti/Mirage-web)

I will also post an update in the Hacktoberfest Discord server once it's open for contributions, so keep an eye out for that announcement! 🛠️💬

Looking forward to your contributions and ideas. Let's make the web UI amazing! 🚀✨

**Comment by Garrett04** [comment]
I'm thinking of React, TailwindCSS, and Redux

**Comment by KorryKatti** [comment]
> I'm thinking of React, TailwindCSS, and Redux. By the way, Is the backend server ready?

the main required endpoints of backend is ready , written in python. i will push the initial web ui code here and then we can kick off with accepting contributions

**Comment by KorryKatti** [comment]
move all convos about web ui to [here](https://github.com/KorryKatti/Mirage-web/issues/1)
