### ISSUE TITLE
Add User Authentication 

### ISSUE THREAD

**Issue by MRELEC1R0N** [KorryKatti/Mirage#30]
Enhancing security by adding user authentication to ensure that only registered users can join rooms and send messages.

**Comment by KorryKatti** [comment]
how do you plan on authenticating the user

**Comment by MRELEC1R0N** [comment]
@KorryKatti  I am planning to use flask or django to autheticate users by navigating them to login page on browser and store there credentials

**Comment by KorryKatti** [comment]
> @KorryKatti I am planning to use flask or django to autheticate users by navigating them to login page on browser and store there credentials

sounds cool , let me integrate the other PRs and then i will open this issue

**Comment by KorryKatti** [comment]
closing right now @MRELEC1R0N but will open in a week
