### ISSUE TITLE
Fix server restart and client issues

### ISSUE THREAD

**Issue by KorryKatti** [KorryKatti/Mirage#32]
#### Description
Currently, the server passes messages between clients as expected, and the client successfully receives these messages. However, the issue arises when the server is restarted — all messages in the client's chat interface disappear.

While it's true that the server does not retain messages in-memory, Mirage saves all messages to a folder named `messages`, where each room has its own text file. To solve this issue, the client could read messages from the corresponding text file upon reconnecting to the server. This way, messages would still be available even after a server restart, significantly improving user experience.

#### How to Reproduce the Issue on Your Local Environment
1. **Run the `server.py`** once.
2. **Copy `client.py`** to two different locations and launch both instances.
3. **Join the Same Room** from both clients and start sending messages.
4. You will notice that **messages are exchanged correctly** between both clients.
5. **Restart the server**.
6. Try to **reconnect to the room** with either client — you will notice that **all messages are gone** from the client view.
7. **Check the corresponding text file** in the `messages` folder — it has all the messages from that room saved.

#### Proposed Solution
To address this issue, the client can read the saved messages from the room's text file upon reconnecting. This would ensure that messages persist in the client's interface, even after a server restart.

#### Action Items
Interested contributors, please review the server and client code, and propose changes to improve the client's behavior regarding message persistence.

**Comment by Manbendra2014** [comment]
Hey ! I'd be happy to help you with improving the client code.

**Comment by KorryKatti** [comment]
assigning

**Comment by KorryKatti** [comment]
fixed now at #33
