### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by KorryKatti** [KorryKatti/Mirage#37]
### Overview
While Mirage does not store data, the messages currently pass through the server in plain text. To enhance security, we need to implement encryption for these messages.

### Task
Your objective is to encrypt the message passing so that messages are only decrypted on the client side.

### Requirements
- Implement encryption for messages transmitted through the server.
- Ensure that messages are decrypted exclusively on the client side.

### Questions or Claims
If you have any doubts or would like to be assigned to this issue, please comment below.

---

### Note
This is part of Hacktoberfest! Let's make Mirage more secure together!

**Comment by Reterics** [comment]
Hi @KorryKatti ,

Can you assign me this issue?

**Comment by KorryKatti** [comment]
> Hi @KorryKatti ,
> 
> Can you assign me this issue?

sure

**Comment by Reterics** [comment]
Thank you, I added a[ PR for this](https://github.com/KorryKatti/Mirage/pull/38)

**Comment by KorryKatti** [comment]
> Thank you, I added a[ PR for this](https://github.com/KorryKatti/Mirage/pull/38)

will test and merge soon , thanks for the PR

**Comment by KorryKatti** [comment]
solved at #38
