### ISSUE TITLE
User profile pages ( public )

### ISSUE THREAD

**Issue by KorryKatti** [KorryKatti/Mirage#43]
### User Profile Pages (Public)

The server currently uses Socket.IO for all communications, and there is no problem with that. Create separate Flask backend pages for all users, which could be accessed at `{url}/~username`.

#### Example:
- For the user **KorryKatti**, the public URL would be: 
  - `https://example.com/~KorryKatti`

#### Requirements:
- The page should be designed in dark mode.
- The user display panel should be arranged as follows:
```
----------------------------------------------------
|   [ Profile Picture ]    Username: KorryKatti    |
|                                                  |
|   Description: Enthusiastic coder working on     |
|   Mirage and contributing to Hacktoberfest.      |
----------------------------------------------------
```
- **Profile Picture (PFP)**: Positioned on the left, sized at 150px x 150px.
- **Username**: Displayed to the right of the profile picture, bold and around 24px in size.
- **Description**: Located just below the username. This field is optional but will be included when present.

All elements should be enclosed in a rectangle, as they will later be integrated into the Mirage client.

**Note:** This issue will activate when #42 has been resolved.

Comment if any doubts

**Comment by ishitab02** [comment]
hey, can you please assign this to me?

**Comment by KorryKatti** [comment]
> hey, can you please assign this to me?

this starts when #42 is done , so if you could wait it would be good

**Comment by ishitab02** [comment]
sure, I will
