### ISSUE TITLE
Set up virtual environment 

### ISSUE THREAD

**Issue by AnanteshG** [KorryKatti/Mirage#44]
To ensure consistent dependency management and avoid conflicts with global Python packages, we need to set up a virtual environment for this project. This will also make it easier for contributors to work in isolated environments.

### Tasks:-
- Set up a virtual environment in the project directory.
- Update the .gitignore file to exclude the virtual environment folder.
- Install required dependencies (if any) and freeze them into a requirements.txt file.
- Add instructions to the README on how to activate the virtual environment and install dependencies.

**Comment by KorryKatti** [comment]
no need for it , everyone knows how to make a venv and install packages
