### ISSUE TITLE
[ Enhancement ] Refactoring the code, Touching up the file structure.

### ISSUE THREAD

**Issue by nub-rin** [KorryKatti/Mirage#45]
As discussed in issue #42 I have made an example enhancement to show you. Kindly refer to the screenshot below.

# Changes
`Proposed file structure, not yet worked on refactoring`
![image](https://github.com/user-attachments/assets/6fcb6e00-9c07-422f-bd27-f67764b83d71)

# Does it still work after file changes? Yes.
![image](https://github.com/user-attachments/assets/4a2fe752-9382-4489-b622-d8e212541e4e)

Basic idea is just to split up code into even smaller files and their designated folder, for example the server in the backend and all the other things related to it etc to make the code more readable and easier to work on. 

Let me know if this sounds cool to you so that I can start working on it further.

**Comment by KorryKatti** [comment]
@nub-rin , copy paste the client.py , userinfo.json and client folder which has encryption data to two other locations , change the username for each of it in the json file and check if messages are going through.

looks good overall

**Comment by nub-rin** [comment]
@KorryKatti Works Flawlessly! Also found something in `server.py`. There is no use of `user_file` and `get_username()` in `server.py`. 

Here is a screenshot of it working.

# Multiple Users
![image](https://github.com/user-attachments/assets/2c359f61-6216-40ef-9100-0871e9f979c6)

# Codebase
![image](https://github.com/user-attachments/assets/27e15c0f-2a3f-40f1-896e-8b680df8c903)

Just have to change the file name of userjson in specific client file but I guess with future implementation of #42 it will not be necessary.

**Comment by KorryKatti** [comment]
> @KorryKatti Works Flawlessly! Also found something in `server.py`. There is no use of `user_file` and `get_username()` in `server.py`.
> 
> Here is a screenshot of it working.
> 
> # Multiple Users
> ![image](https://private-user-images.githubusercontent.com/82444564/378118701-2c359f61-6216-40ef-9100-0871e9f979c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzODc1NTMsIm5iZiI6MTcyOTM4NzI1MywicGF0aCI6Ii84MjQ0NDU2NC8zNzgxMTg3MDEtMmMzNTlmNjEtNjIxNi00MGVmLTkxMDAtMDg3MWU5Zjk3OWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDAxMjA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYWE2MjczNmQwZGVmMGU0YWJiZjUxNjI4ZTA2Y2NhYmU3MjQ5MzZjZGYwMmMxN2NmMzQ4MDE1NDQ5NDMzNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LqOZVnmZV9-QPk2kqMkfWhs8YZZDRRwzVu4q_QsKEKE)
> 
> # Codebase
> ![image](https://private-user-images.githubusercontent.com/82444564/378118712-27e15c0f-2a3f-40f1-896e-8b680df8c903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzODc1NTMsIm5iZiI6MTcyOTM4NzI1MywicGF0aCI6Ii84MjQ0NDU2NC8zNzgxMTg3MTItMjdlMTVjMGYtMmEzZi00MGYxLTg5NmUtOGI2ODBkZjhjOTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDAxMjA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NDgyZGM2ODAzMWI1YWQyNmRkZjg3ZGE4ZGJkOTJlZTc0NDQzN2NjMDA2YzhiYjlkZTFmOGRhZjI0YzQxYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9tH9WpX89pFcYvnXVFqL5P-ABGjV8zy_a4dej4TGwGQ)
> 
> Just have to change the file name of userjson in specific client file but I guess with future implementation of #42 it will not be necessary.
> 
> EDIT:
> 
> # Messages.txt
> (Whoever created the room in this case `user`, it'll update their specific `message.txt`) ![image](https://private-user-images.githubusercontent.com/82444564/378118870-f966ac54-2bd4-4b01-ba76-35214b5a9ac7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzODc1NTMsIm5iZiI6MTcyOTM4NzI1MywicGF0aCI6Ii84MjQ0NDU2NC8zNzgxMTg4NzAtZjk2NmFjNTQtMmJkNC00YjAxLWJhNzYtMzUyMTRiNWE5YWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDAxMjA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNDg5OTRhMjAxODNiYWNhODlhMDdmZTUwMjc2NGE5Y2IzMWIyNmVkNGFjZTVhMGUwZTc2ODg5OGI1YmU2MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lwqnmVhu7BvtWpk3Uduh_bj8cHDbxad89j_wtfVkE6s)

cool , please do make a PR and i will review and merge it

**Comment by KorryKatti** [comment]
@nub-rin any updates ?

**Comment by nub-rin** [comment]
> @nub-rin any updates ?

Hi sorry, I had to travel. Will finish it up till tomorrow and send a PR for you to check.

**Comment by KorryKatti** [comment]
> > @nub-rin any updates ?
> 
> Hi sorry, I had to travel. Will finish it up till tomorrow and send a PR for you to check.

np , happy journey

**Comment by nub-rin** [comment]
Hi @KorryKatti Sorry it took long, but will be providing with a PR in a few hours from now possibly. Just quickly running a few tests and finalizing last min things. After this I will start trying to work on #42 and see how to approach it efficiently.

**Comment by KorryKatti** [comment]
> Hi @KorryKatti Sorry it took long, but will be providing with a PR in a few hours from now possibly. Just quickly running a few tests and finalizing last min things. After this I will start trying to work on #42 and see how to approach it efficiently.

fine , i will be waiting for the PR . I might take some time to check it as a cyclone is coming over at where i am right now but i will try my best

**Comment by nub-rin** [comment]
Hi not a problem at all, I think the concerns for a cyclone are more important! Take care!!

**Comment by KorryKatti** [comment]
solved with #46 , will reopen when more refactoring needed , currently focusing on #42
