### ISSUE TITLE
Future Planning

### ISSUE THREAD

**Issue by KorryKatti** [KorryKatti/Mirage#9]
Here i will put on things which will be open in the future weeks in hacktoberfest for Mirage. 

Comment below to let me know which you are interested in and i will ping you when i open the issue

Plan List

- [ ]  switch code to socketio
- [ ] web based chat
- [ ] more secuity

**Comment by TaherTadpatri** [comment]
I am interested in web based chat

**Comment by KorryKatti** [comment]
> I am interested in web based chat

noted

**Comment by spline2hg** [comment]
i can work on socket io part

**Comment by rbcommoncents** [comment]
I may be able to contribute to additional security.

**Comment by KorryKatti** [comment]
> i can work on socket io part

socketio part will open soon

**Comment by KorryKatti** [comment]
> I may be able to contribute to additional security.

after the socketio part is done , that part will open for people to do the encryption stuff

**Comment by spline2hg** [comment]
> > i can work on socket io part
> 
> socketio part will open soon

yeah cool , ping me once available

**Comment by KorryKatti** [comment]
> > > i can work on socket io part
> > 
> > 
> > socketio part will open soon
> 
> yeah cool , ping me once available

you can start working on the server.py now its open for PRs

**Comment by KorryKatti** [comment]
@spline2hg

**Comment by spline2hg** [comment]
hey man whats the update on this , are we  not doing this now, i couldnt get back to u cause i was struck in some work sry for that

**Comment by KorryKatti** [comment]
> hey man whats the update on this , are we not doing this now, i couldnt get back to u cause i was struck in some work sry for that

someone is working on the server , changing its framework from flask based to socket-io , also i have opened the web ui issue for updates. And no this project will be open all hacktoberfest.

**Comment by spline2hg** [comment]
ok sure

**Comment by KorryKatti** [comment]
> I may be able to contribute to additional security.

@rbcommoncents open now #37

**Comment by Reterics** [comment]
> > I may be able to contribute to additional security.
> 
> @rbcommoncents open now #37

I can be the backup dev for the security issue. Just assign it to me if you want me to check it

**Comment by KorryKatti** [comment]
> > > I may be able to contribute to additional security.
> > 
> > 
> > @rbcommoncents open now #37
> 
> I can be the backup dev for the security issue. Just assign it to me if you want me to check it

sure just comment on that issue , i will assign you
